### ISSUE TITLE
Upřesnění zadání

### ISSUE THREAD

**Issue by tomires** [3DprintFIT/B161HW-Template#1]
Měl bych pár dotazů k úkolu.

1. Máme ošetřit nějaké podmínky pro argumenty pin_* a round_r?
2. Mohou platit následující vztahy?
         border_outlet = 0
         depth_of_outlets + pin_depth = z
3. Úhel kolíku pin_angle se počítá od osy Y (tedy kolmo k zásuvce = 90°)? Je ve stupních?
4. Když zvyšuji zaoblení round_r (používám minkowski), musím adekvátně zmenšovat rozměry na všech osách aby se celý objekt nezvětšoval nebo stačí když zajistím aby nezasahoval do záporného z?

Dík

**Comment by syky27** [comment]
@hroncok @jakubprusa Ti snad poradi, ja jsem nepsal zadani.

**Comment by hroncok** [comment]
1. ne
2. border_outlet = 0 => nic se nevykreslí (dopisuji do zadání)
3. ano, ano, směr viz obrázek
4. musíš, jiné uvedené rozměry jsou vnější po zaoblení (dopisuji do zadání)
